"""empty message

Revision ID: f55f0f0fe36a
Revises: 
Create Date: 2022-11-03 18:08:28.526839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55f0f0fe36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('averageVolume', sa.Integer(), nullable=True),
    sa.Column('averageVolume10days', sa.Integer(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('debtToEquity', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Integer(), nullable=True),
    sa.Column('fiftyDayAverage', sa.Float(), nullable=True),
    sa.Column('fiftyTwoWeekHigh', sa.Float(), nullable=True),
    sa.Column('fiftyTwoWeekLow', sa.Float(), nullable=True),
    sa.Column('floatShares', sa.Integer(), nullable=True),
    sa.Column('forwardEps', sa.Float(), nullable=True),
    sa.Column('forwardPE', sa.Float(), nullable=True),
    sa.Column('freeCashflow', sa.Integer(), nullable=True),
    sa.Column('fullTimeEmployees', sa.Integer(), nullable=True),
    sa.Column('grossMargins', sa.Float(), nullable=True),
    sa.Column('grossProfits', sa.Integer(), nullable=True),
    sa.Column('heldPercentInsiders', sa.Float(), nullable=True),
    sa.Column('heldPercentInstitutions', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=200), nullable=True),
    sa.Column('longBusinessSummary', sa.String(length=2000), nullable=True),
    sa.Column('longName', sa.String(length=200), nullable=True),
    sa.Column('marketCap', sa.Integer(), nullable=True),
    sa.Column('operatingCashflow', sa.Integer(), nullable=True),
    sa.Column('operatingMargins', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profitMargins', sa.Float(), nullable=True),
    sa.Column('recommendationKey', sa.String(length=20), nullable=True),
    sa.Column('recommendationMean', sa.Float(), nullable=True),
    sa.Column('revenueGrowth', sa.Float(), nullable=True),
    sa.Column('revenuePerShare', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sharesOutstanding', sa.Integer(), nullable=True),
    sa.Column('sharesShort', sa.Integer(), nullable=True),
    sa.Column('shortName', sa.String(length=100), nullable=True),
    sa.Column('shortPercentOfFloat', sa.Float(), nullable=True),
    sa.Column('shortRatio', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('totalCash', sa.Integer(), nullable=True),
    sa.Column('totalCashPerShare', sa.Float(), nullable=True),
    sa.Column('totalDebt', sa.Integer(), nullable=True),
    sa.Column('totalRevenue', sa.Integer(), nullable=True),
    sa.Column('twoHundredDayAverage', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('note', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_stocks',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    op.drop_table('watchlists')
    op.drop_table('transactions')
    op.drop_table('orders')
    op.drop_table('notes')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
